-- MT5 Trade Logger Database Schema
-- PostgreSQL / Supabase compatible

-- Enable UUID extension if needed
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Trades table
CREATE TABLE IF NOT EXISTS trades (
    id BIGSERIAL PRIMARY KEY,
    
    -- Trade identification
    ticket VARCHAR(100) NOT NULL,
    trade_uid VARCHAR(255) NOT NULL UNIQUE,
    
    -- Account information
    account_mode VARCHAR(20) NOT NULL CHECK (account_mode IN ('simulation', 'demo', 'live')),
    broker VARCHAR(255),
    
    -- Trade details
    symbol VARCHAR(50) NOT NULL,
    side VARCHAR(10) NOT NULL CHECK (side IN ('buy', 'sell')),
    volume DECIMAL(18, 8) NOT NULL,
    
    -- Prices
    price_open DECIMAL(18, 8) NOT NULL,
    price_close DECIMAL(18, 8),
    stop_loss DECIMAL(18, 8),
    take_profit DECIMAL(18, 8),
    
    -- Financials
    pnl DECIMAL(18, 2),
    commission DECIMAL(18, 2) DEFAULT 0,
    swap DECIMAL(18, 2) DEFAULT 0,
    
    -- Trade result
    result VARCHAR(20) CHECK (result IN ('win', 'loss', 'breakeven')),
    r_multiple DECIMAL(18, 4), -- Risk-reward multiple
    
    -- Timestamps
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    duration_seconds INTEGER,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_trades_ticket ON trades(ticket);
CREATE INDEX IF NOT EXISTS idx_trades_trade_uid ON trades(trade_uid);
CREATE INDEX IF NOT EXISTS idx_trades_account_mode ON trades(account_mode);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_opened_at ON trades(opened_at);
CREATE INDEX IF NOT EXISTS idx_trades_closed_at ON trades(closed_at);
CREATE INDEX IF NOT EXISTS idx_trades_ticket_mode ON trades(ticket, account_mode);

-- Composite index for common queries
CREATE INDEX IF NOT EXISTS idx_trades_mode_symbol ON trades(account_mode, symbol);
CREATE INDEX IF NOT EXISTS idx_trades_mode_opened ON trades(account_mode, opened_at DESC);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to auto-update updated_at
CREATE TRIGGER update_trades_updated_at 
    BEFORE UPDATE ON trades 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- View for open trades
CREATE OR REPLACE VIEW open_trades AS
SELECT 
    id,
    ticket,
    trade_uid,
    account_mode,
    broker,
    symbol,
    side,
    volume,
    price_open,
    stop_loss,
    take_profit,
    opened_at,
    EXTRACT(EPOCH FROM (NOW() - opened_at))::INTEGER AS duration_seconds_open,
    created_at
FROM trades
WHERE closed_at IS NULL
ORDER BY opened_at DESC;

-- View for closed trades with calculated metrics
CREATE OR REPLACE VIEW closed_trades AS
SELECT 
    id,
    ticket,
    trade_uid,
    account_mode,
    broker,
    symbol,
    side,
    volume,
    price_open,
    price_close,
    stop_loss,
    take_profit,
    pnl,
    commission,
    swap,
    result,
    r_multiple,
    opened_at,
    closed_at,
    duration_seconds,
    created_at,
    updated_at
FROM trades
WHERE closed_at IS NOT NULL
ORDER BY closed_at DESC;

-- Comments for documentation
COMMENT ON TABLE trades IS 'Stores all trades from MT5 Expert Advisor';
COMMENT ON COLUMN trades.ticket IS 'MT5 position ticket';
COMMENT ON COLUMN trades.trade_uid IS 'Unique identifier generated by EA';
COMMENT ON COLUMN trades.account_mode IS 'Account mode: simulation, demo, or live';
COMMENT ON COLUMN trades.r_multiple IS 'Risk-reward multiple (PnL / Risk Amount)';
COMMENT ON COLUMN trades.duration_seconds IS 'Trade duration in seconds';

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Habilitar RLS en la tabla trades
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

-- Política 1: Permitir todo al service_role (backend/API)
-- El backend usa service_role para todas las operaciones
CREATE POLICY "Allow all operations for service_role"
ON trades
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Política 2: Permitir lectura a usuarios autenticados (opcional para frontend)
-- Si tu frontend se conecta directamente a Supabase, descomenta esto:
-- CREATE POLICY "Allow read for authenticated users"
-- ON trades
-- FOR SELECT
-- TO authenticated
-- USING (true);

-- NOTA: Si solo el backend accede a la base de datos (como en este caso),
-- solo necesitas la política del service_role. Las otras políticas son opcionales.

